name: StarsWaehrung
version: 1.0-SNAPSHOT
main: de.mitoo.starswaehrung.StarsWaehrung
api-version: '1.20'
author: Mitoo
commands:
  stars:
    description: Eine Währung
    usage: /stars <set|give|see|take|reset> <player> [amount]
